core: &core
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  port: 5432
  username: postgres
  password: 123456789

development:
  <<: *core
  database: prelaunchr_development

test:
  <<: *core
  database: prolaunchr_test
